language: cpp
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
before_install:
- |
  # Installs conda
  wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  bash miniconda.sh -b -p $HOME/miniconda
  export PATH="$HOME/miniconda/bin:$PATH"
  conda config --set always_yes yes --set changeps1 no
  conda config --add channels conda-forge
  conda update -q conda
install:
- |
  # Configures to use GCC 7
  export CC=gcc-7
  export CXX=g++-7

  # Creates a conda environment that contains only nlohmann_json and CMake
  conda create -c conda-forge -n hello_json "nlohmann_json>=3.5.0" "cmake>=3.10" --no-default-packages

  # Activates this environment (puts things on PATH and configure environment variables that may be needed)
  source activate hello_json

  # Builds the code using CMake
  mkdir -p build && cd build
  cmake .. -G "Unix Makefiles"
  cmake --build . --config Release
script:
- ./hello_json
